Add homework-30 solution
BilkoYevgen/Homeworks pull request #18
Opened 2023-03-22 01:53 UTC by BilkoYevgen

Check it please

2023-03-25 18:27 UTC, klymenok requested changes

2023-03-25 18:27 UTC, klymenok commented on HW-30/main.py
> +latitude = round(data["results"][0]["latitude"], 2)
Тут виникне помилка, якщо користувач введе назву міста, якого не існує

2023-03-26 13:23 UTC, BilkoYevgen commented on HW-30/main.py
> +latitude = round(data["results"][0]["latitude"], 2)
Зараз має бути краще

2023-03-27 20:21 UTC, klymenok approved these changes
Looks good!

2023-03-27 20:49 UTC, merged