Add HW-36 solution
BilkoYevgen/Homeworks pull request #22
Opened 2023-04-11 21:03 UTC by BilkoYevgen

2023-04-14 15:35 UTC, klymenok requested changes

2023-04-14 15:35 UTC, klymenok commented on HW-31/flask-homework/my_app/views.py
> +    all_purchase = Purchase.query.all()
Використайте тут пошук за значенням у зверненні до бази даних, замість того, щоб фільтрувати у вашому коді:
`purchase = Purchase.query.get(purchases_id)`

2023-04-14 15:35 UTC, klymenok commented on HW-31/flask-homework/my_app/views.py
> +@app.route('/purchase')
endpoint має називатися purchases

2023-04-14 15:35 UTC, klymenok commented on HW-31/flask-homework/my_app/views.py
> +    all_books = Book.query.all()
Тут можна одразу отримати необхідну книжку `book = Book.query.get(book_id)`

2023-04-14 15:35 UTC, klymenok commented on HW-31/flask-homework/my_app/views.py
> +                'title': book1[0].title,
Код співпадає із кодом іншого студента. Прохання написати ваше власне вирішення ДЗ

2023-04-14 18:03 UTC, BilkoYevgen commented on HW-31/flask-homework/my_app/views.py
> +                'title': book1[0].title,
Вибачте. Я справді надихався роботою одного з учнів. Сів навчати Django, у голові повна каша, терміни горять, ось і вирішив схитрувати. Зрештою потім переробив, але пушити вже не вирішив.

2023-04-17 20:34 UTC, klymenok commented on HW-31/flask-homework/my_app/views.py
> +                'title': book1[0].title,
Ви вибрали не зовсім вдалий приклад для наслідування

2023-04-17 20:40 UTC, klymenok requested changes

2023-04-17 20:40 UTC, klymenok commented on HW-31/flask-homework/my_app/views.py
> +    if 'size' in request.args:
Ви можете передати size в ORM для здійснення ліміту на рівні бази даних за допомогою методу .limit(n). Якщо у вас база буде містити 10 М обʼєктів, то цей код буде дуже уповільнювати вашу роботу. Це саме стосується і інших ендпоінтів.

2023-04-17 20:40 UTC, klymenok commented on HW-31/flask-homework/my_app/views.py
> +        book = Book.query.get(purchase.book_id)
Purchase вже містить звʼязки і ви можете їх використати:
```
purchase.user.first_name
purchase.book.title
```

2023-04-17 20:40 UTC, klymenok commented on HW-31/flask-homework/my_app/views.py
> +        book = Book.query.get(purchase.book_id)
Purchase вже містить звʼязки і ви можете їх використати:
```
purchase.user.first_name
purchase.book.title
```

2023-04-18 15:00 UTC, BilkoYevgen commented on HW-31/flask-homework/my_app/views.py
> +        book = Book.query.get(purchase.book_id)
виправив

2023-04-18 15:00 UTC, BilkoYevgen commented on HW-31/flask-homework/my_app/views.py
> +        book = Book.query.get(purchase.book_id)
виправив

2023-04-18 15:01 UTC, BilkoYevgen commented on HW-31/flask-homework/my_app/views.py
> +    if 'size' in request.args:
Виправив. Сподіваюся зараз буде краще)

2023-04-21 15:33 UTC, klymenok approved these changes
Ви могли використати існуючі темплейти для того, щоб відобразити дані

2023-04-22 13:45 UTC, merged