Add solution for HW-40
BilkoYevgen/Homeworks pull request #28
Opened 2023-04-22 14:45 UTC by BilkoYevgen

2023-04-23 11:18 UTC, klymenok requested changes

2023-04-23 11:18 UTC, klymenok commented on HW-38/book/models.py
> +    title = models.CharField(max_length=200, verbose_name='Назва')
Для цих змін потрібно виконати створити міграції

2023-04-23 11:18 UTC, klymenok commented on HW-38/purchase/models.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Користувач")
Для цих змін потрібно створити міграції

2023-04-23 11:18 UTC, klymenok commented on HW-38/user/models.py
> +    first_name = models.CharField(max_length=50, verbose_name="Ім'я")
Для цих змін потрібно створити міграції

2023-04-23 14:34 UTC, BilkoYevgen commented on HW-38/book/models.py
> +    title = models.CharField(max_length=200, verbose_name='Назва')
Дуже дякую за виправлення.  Код чомусь працював без міграцій.  В інтернеті відповіді на це питання я не знайшов.  Так як це не створення моделі, а лише присвоєння імені, вирішив їх не робити.

2023-04-25 18:12 UTC, klymenok approved these changes
Looks good!

2023-04-25 18:46 UTC, merged