Add solution for HW-42
BilkoYevgen/Homeworks pull request #31
Opened 2023-05-02 16:49 UTC by BilkoYevgen

2023-05-03 11:39 UTC, klymenok requested changes

2023-05-03 11:39 UTC, klymenok commented on HW-38/purchase/serializers.py
> +    user = serializers.SerializerMethodField()
Так краще не робити, оскільки ці 2 атрибути це окремі обʼєкти в базі даних і тут доцільніше було б використати або відображення id за замовчуванням, або вкладений серіалайзер UserSerializer та BookSerializer.
Таким чином, отримавши дані про покупки, можна буде отримати id користувача та книжки і здійснити додаткові дії з цими даними

2023-05-03 14:49 UTC, BilkoYevgen commented on HW-38/purchase/serializers.py
> +    user = serializers.SerializerMethodField()
Дуже дякую, ніколи б не подумав. Якщо я правильно зрозумів, то зараз має бути краще

2023-05-08 11:17 UTC, klymenok commented on HW-38/purchase/serializers.py
> +    user = serializers.SerializerMethodField()
Взагалі можна не визначати ці атрибути вручну, а залишити поведінку за замовчуванням

2023-05-08 11:17 UTC, klymenok approved these changes

2023-05-08 11:58 UTC, merged