Homework 44
BilkoYevgen/Homeworks pull request #32
Opened 2023-05-07 12:57 UTC by BilkoYevgen

2023-05-08 11:56 UTC, klymenok requested changes

2023-05-08 11:56 UTC, klymenok commented on HW-38/purchase/views.py
> +На жаль, пошук тут не буде працювати корректно, через використання ForeignKey, для коректної роботи потрібно
Можливо краще тоді не робити те, що буде працювати некоректно?

Можете спробувати фільтрувати не по значенням id, а бо полям повʼязаних обʼєктів. Наприклад, 
`'user__first_name': ['contains', 'exact'],`

2023-05-08 11:56 UTC, klymenok commented on HW-38/user/views.py
> +class UserAPIView(generics.ListAPIView):
Зайвий view клас

2023-05-08 11:56 UTC, klymenok commented on HW-38/purchase/views.py
> +class PurchaseAPIView(generics.ListAPIView):
Зайвий view клас

2023-05-08 11:56 UTC, klymenok commented on HW-38/book/views.py
> +class BookAPIView(generics.ListAPIView):
Зайвий view клас

2023-05-08 23:28 UTC, BilkoYevgen commented on HW-38/purchase/views.py
> +На жаль, пошук тут не буде працювати корректно, через використання ForeignKey, для коректної роботи потрібно
Спасибі за підказку. Зробив

2023-05-11 16:43 UTC, klymenok approved these changes

2023-05-11 16:53 UTC, merged