Add Homework-7 solution
BilkoYevgen/Homeworks pull request #5
Opened 2022-12-23 23:40 UTC by BilkoYevgen

Вирішив трохи ускладнити собі завдання. Було важливо зробити щоб input взяв та delete та аргумент. Начебто вийшло)

Номер телефону має бути валідний і зі знаком +

2022-12-23 23:46 UTC, BilkoYevgen commented
З якоїсь причини перший коміт був порожнім. Виправив

2022-12-27 19:58 UTC, klymenok requested changes

2022-12-27 19:58 UTC, klymenok commented on HW-07/main.py
> +            command = ''
You should move this line outside this for-in because in case of an empty phonebook, your program stuck here

2022-12-27 20:26 UTC, BilkoYevgen commented on HW-07/main.py
> +            command = ''
Цілком згоден, виправив.

2023-01-04 21:28 UTC, klymenok approved these changes
Looks good!

2023-01-04 21:36 UTC, merged